---
- name: Install Docker Engine and Docker Compose
  hosts: doc
  become: true

  tasks:
    - name: Install Docker Engine packages
      yum:
        name:
          - yum-utils
          - device-mapper-persistent-data
          - lvm2
        state: present

    - name: Configure the docker-ce repo
      command: yum-config-manager --add-repo https://download.docker.com/linux/centos/docker-ce.repo

    - name: Install docker-ce
      yum:
        name: docker-ce
        state: present

    - name: Start and enable Docker serivce
      service:
        name: docker.service
        state: started
        enabled: true

    - name: Install Docker-compose packages
      yum:
        name:
          - epel-release
          - python3-pip
        state: present            

    - name: Enable Epel extra repo
      yum:
        name: epel-release
        enablerepo: extras
        state: present     

    - name: stop firewalld
      service:
        name: firewalld
        state: stopped    